package com.echameunapata.backend.domain.enums.notifications;

public enum NotificationType {
    REPORT_CREATED,
    REPORT_STATUS_CHANGED,
    USER_REGISTERED,
    FORGOT_PASSWORD,
    GENERIC_MESSAGE,
    ADOPTION_APPLICATION_REGISTERED,
    ADOPTION_APPLICATION_APPROVED,
    ADOPTION_APPLICATION_REJECTED;
}
